// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdMcDpQ7NDR9bns1KipqX8ZbHJprO5xz0',
    appId: '1:15756766448:web:777dec9d5b153188f7a635',
    messagingSenderId: '15756766448',
    projectId: 'marketplace-caeae',
    authDomain: 'marketplace-caeae.firebaseapp.com',
    storageBucket: 'marketplace-caeae.appspot.com',
    measurementId: 'G-NJ14D0CZ30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi4qUXSf_iUJkt6di9VNYrX_A9pgRSb0Y',
    appId: '1:15756766448:android:485d7a58fb578243f7a635',
    messagingSenderId: '15756766448',
    projectId: 'marketplace-caeae',
    storageBucket: 'marketplace-caeae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSWNlVwxYC2b5SItl5Bcma409LdJvL99A',
    appId: '1:15756766448:ios:cae425eff1bb09a9f7a635',
    messagingSenderId: '15756766448',
    projectId: 'marketplace-caeae',
    storageBucket: 'marketplace-caeae.appspot.com',
    iosClientId: '15756766448-d47dou2amc4ol9fmrjvcdr10ntr04drl.apps.googleusercontent.com',
    iosBundleId: 'com.example.softMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSWNlVwxYC2b5SItl5Bcma409LdJvL99A',
    appId: '1:15756766448:ios:cae425eff1bb09a9f7a635',
    messagingSenderId: '15756766448',
    projectId: 'marketplace-caeae',
    storageBucket: 'marketplace-caeae.appspot.com',
    iosClientId: '15756766448-d47dou2amc4ol9fmrjvcdr10ntr04drl.apps.googleusercontent.com',
    iosBundleId: 'com.example.softMarket',
  );
}
